### PR TITLE
Fix for backuptools and a nifty logo for TWRP

### PR DESCRIPTION
**Pull request by anirudhgupta109**

### CODE REVIEW

**Comment by anupritaisno1** [comment]
Useless. You basically picked a commit, then reverted it, picked it back and reverted it again

Use git rebase to remove the useless commits and squash any insignificant changes

**Comment by anupritaisno1** [comment]
337b22888bf0a75616e06fb9b58e3931d9f8f9d1 has an invalid commit message 
Why? Commit message is ambiguous, doesn't describe the change. Also I think you meant "The entire thing can't be displayed on TWRP" instead of "The entries thing can't be displayed on TWRP"

82ef7060a0638c8d395f248ddebcad58c8753740 too. I don't care how frustrated you are. describe your change correctly and this change is again insignificant. squash it

**Comment by anirudhgupta109** [comment]
@anupritaisno1 I've already closed it, before you mentioned it, please take a look before commenting further

**Comment by anirudhgupta109** [comment]
@anupritaisno1 82ef is significant, you'd understand when building, indentation errors pop-up, you clearly have not tried it before so please try it once before commenting
337b was an auto-correct reason why I said I closed it, next time, check before you speak

**Comment by anupritaisno1** [comment]
82ef is insignificant and occurred because you derped bddccea52ad61b97e4354a67425972972eb6be1a

Squash it onto bddccea52ad61b97e4354a67425972972eb6be1a and stop trying to show how right you are

**Comment by anupritaisno1** [comment]
Without bddccea52ad61b97e4354a67425972972eb6be1a 82ef wouldn't have existed and it doesn't bring any code changes

**Comment by anirudhgupta109** [comment]
@anupritaisno1 Well me derping is cause I actually tried, having multiple commits for the same thing wouldn't be an issue if in the end it adds something, last I checked, I haven't seen you do anything except act like a boss for something I see no code contributed to in the recent past.

I'm not trying to show how right I am, I'm showing how delusional you are

**Comment by anupritaisno1** [comment]
Tell me if we decide to rebase aim 6 months later and read this shit "TIL that indentation matters.. smfh.." will we even know what this is? No, also this commit has occured because you made a mistake in a previous commit so you should squash it onto the previous commit

**Comment by anupritaisno1** [comment]
I could understand if you're correcting a change that was already merged but this isn't and you can easily combine this change into a single commit as your follow up fixes are downright stupid because such a mistake shouldn't have happened in the first place

Got a good reason for the 4 useless commits you're asking them to merge?

**Comment by anirudhgupta109** [comment]
@anupritaisno1 I'd be around to help if you won't like I am right now, and I do agree that it's a mistake, reason why I closed it immediately, but you making a big deal out of it won't help neither you nor me nor the team

**Comment by anupritaisno1** [comment]
This kind of shit is honestly why we need a Gerrit

**Comment by anirudhgupta109** [comment]
@anupritaisno1 +1

**Pull request closed without merging**
